
version: '3'

services:
  bidaltzen:
    build:
      context: ./defBarruan
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DEST_IP=192.168.1.1
      - BASH_COMMAND='tail -n4 /etc/passwd'
    networks:
      - custom_network
    depends_on:
      - erantzuten

  erantzuten:
    build:
      context: ./erasotsaileaKanpoan
      dockerfile: Dockerfile
    privileged: true
    environment:
      - LISTEN_IP=0.0.0.0
    networks:
      - custom_network
    volumes:
      - ./jasotakoa:/root

networks:
  custom_network:
    driver: bridge

volumes:
  jasotakoa:
    driver: local